packaging_format = 2

id = "cultivons"
name = "Cultivons"
description.en = "Sustainable Autonomous Base Manager"
description.fr = "Gestionnaire de Base Autonome Durable"

version = "1.0~ynh1"

maintainers = ["Pierre Levasseur"]

[upstream]
license = "Apache-2.0"
website = "https://xulops.net/forge/cultivons.php"
demo = "https://cultivons-demo.xulops.net"
admindoc = "https://xulops.net/forge/cultivons.php?menu=about"
userdoc = "https://xulops.net/forge/cultivons.php?menu=about"
code = "https://xulops.net/forge/cultivons.php?menu=download"

[integration]
yunohost = ">= 11.1.20"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.fr = "Cette page sera accessible par n'importe qui. En revanche, la configuration reste personnelle"
    help.en = "The page will be accessible by anyone."
    type = "group"
    default = false

[resources]
        [resources.sources.main]
        url = "https://xulops.net/forge/cultivons.php?f=download&pk=42&v=72362bd6539335892871e8189eb85591"
        sha256 = "5fdad5ab3ad5052008277f3c456e90bbecbe7ec2f52d84e1fa9333f9a8c41d5c"
        in_subdir = false


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-sqlite3"
