packaging_format = 2

id = "cultivons"
name = "Cultivons"
description.en = "Sustainable Autonomous Base Manager"
description.fr = "Gestionnaire de Base Autonome Durable"

version = "1.9~ynh1"

maintainers = ["Pierre Levasseur"]

[upstream]
license = "Apache-2.0"
website = "https://xulops.net/forge/cultivons.php"
demo = "https://cultivons-demo.xulops.net"
admindoc = "https://xulops.net/forge/cultivons.php?menu=about"
userdoc = "https://xulops.net/forge/cultivons.php?menu=about"
code = "https://xulops.net/forge/cultivons.php?menu=download"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.fr = "Si 'visiteurs' est sélectionné, cette page sera accessible par n'importe qui. En revanche, la configuration reste personnelle"
    help.en = "If 'visitors' is selected, the page will be accessible by anyone. However, the configuration will still remain private."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://xulops.net/forge/cultivons.php?f=download&pk=53&v=9d9f29f852f64b680662ac25d08117f8"
        sha256 = "197b76cefb3ac60f8abdac313cd9162d87d4c1e6d3b882741a8d5730ed66631c"
        extract = true
        in_subdir = false
        format = "zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-fpm, php8.0-sqlite3"
